// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnyoqOh9LP_812gHKmROGd-EGv5jeRYLU',
    appId: '1:1017457108382:web:c1664e9b011c542f49228f',
    messagingSenderId: '1017457108382',
    projectId: 'skinspy-f9079',
    authDomain: 'skinspy-f9079.firebaseapp.com',
    storageBucket: 'skinspy-f9079.appspot.com',
    measurementId: 'G-6T6LF19PM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSmaz0FiLy2YdRI50vh5YuPonzf2K5nOs',
    appId: '1:1017457108382:android:b9e00bbe76c64a6049228f',
    messagingSenderId: '1017457108382',
    projectId: 'skinspy-f9079',
    storageBucket: 'skinspy-f9079.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAire84FNkyjck21gb-zcID9WyQTmUpEpA',
    appId: '1:1017457108382:ios:0fd7548f85d00dfe49228f',
    messagingSenderId: '1017457108382',
    projectId: 'skinspy-f9079',
    storageBucket: 'skinspy-f9079.appspot.com',
    iosBundleId: 'com.example.skinspy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAire84FNkyjck21gb-zcID9WyQTmUpEpA',
    appId: '1:1017457108382:ios:adb0106db78fc9b149228f',
    messagingSenderId: '1017457108382',
    projectId: 'skinspy-f9079',
    storageBucket: 'skinspy-f9079.appspot.com',
    iosBundleId: 'com.example.skinspy.RunnerTests',
  );
}
